on:
  workflow_dispatch:
  push:
    branches:
      - prod
jobs:
  npm_publish:
    uses: 'nickeltin1/reusable-workflows/.github/workflows/npm-publish.yml@main'
    with:
      registry-url: https://nickeltin-private.glitch.me/