on:
  workflow_dispatch:

jobs:
  npm_publish:
    uses: 'nickeltin1/reusable-workflows/.github/workflows/npm_publish.yml@main'
    with:
      registry_url: https://nickeltin-private.glitch.me/
    secrets: inherit
