# Mirrors pushes from prod to public branch

on: 
  workflow_dispatch:
  push:
    branches:
      - prod
      
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "nickeltin1/nickeltin-core"
          source_branch: "prod"
          destination_repo: "nickeltin1/nickeltin-core-public"
          destination_branch: "main"
